### PR TITLE
refactor(autoware_auto_control_msgs): replace autoware_auto_control_msgs with autoware_control_msgs

### PR DESCRIPTION
**Pull request by xmfcx**
## PR Type

- Refactor

## Related Links

- https://github.com/autowarefoundation/autoware.universe/issues/3674
- https://github.com/autowarefoundation/autoware.universe/pull/3677
- https://github.com/tier4/tier4_ad_api_adaptor/pull/106
- https://github.com/autowarefoundation/autoware_launch/pull/353

## Description

Replace all usages of

- https://github.com/tier4/autoware_auto_msgs/tree/tier4/main/autoware_auto_control_msgs/msg
with
- https://github.com/autowarefoundation/autoware_msgs/tree/main/autoware_control_msgs/msg

## Review Procedure

Make sure it compiles with the rest of the Autoware once it is merged along with the Autoware Universe PR:
- https://github.com/autowarefoundation/autoware.universe/pull/3677
- https://github.com/tier4/tier4_ad_api_adaptor/pull/106
- https://github.com/autowarefoundation/autoware_launch/pull/353

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

### CODE REVIEW

**Comment by xmfcx** [comment]
@isamu-takagi @mitsudome-r could you review this too?

**Comment by isamu-takagi** [comment]
@xmfcx @TakaHoribe @TomohitoAndo @aohsato 
Could you ask the maintainer for a review? It's probably good, but I'm not familiar with this package.

**Comment by xmfcx** [comment]
@tkimura4 you seem to be a maintainer of this package, could you look into this too? (I cannot assign reviewers.)

**Review by tkimura4 — APPROVED** [review]
Thank you! It looks good.

**Comment by xmfcx** [comment]
I'm closing all of my message migration PRs.

**Pull request closed without merging**
